import React, { createContext, useContext, useState, useEffect } from 'react';

// Comprehensive translations for the application
const translations = {
  en: {
    // Common
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    import: 'Import',
    yes: 'Yes',
    no: 'No',
    close: 'Close',
    submit: 'Submit',

    // Navigation
    home: 'Home',
    dashboard: 'Dashboard',
    products: 'Products',
    marketplace: 'Marketplace',
    inventory: 'Inventory',
    processing: 'Processing Services',
    education: 'Education & Training',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Logout',
    login: 'Login',

    // Dashboard
    totalBatches: 'Total Batches',
    totalOrders: 'Total Orders',
    totalSales: 'Total Sales',
    rating: 'Rating',
    reviews: 'Reviews',
    approvedSales: 'Approved Sales',
    totalRevenue: 'Total Revenue',
    delivered: 'Delivered',
    inTransit: 'In Transit',
    totalSpent: 'Total Spent',
    applications: 'Applications',
    totalValue: 'Total Value',
    pendingInspection: 'Pending Inspection',
    inspectedToday: 'Inspected Today',
    gradeABatches: 'Grade A+ Batches',
    totalInspections: 'Total Inspections',
    quickActions: 'Quick Actions',
    sales: 'Sales',
    training: 'Training',
    shopNow: 'Shop Now',
    cart: 'Cart',
    trackOrders: 'Track Orders',
    adminPanel: 'Admin Panel',
    marketInfo: 'Market Info',
    qualityAssessment: 'Quality Assessment',
    batchLookup: 'Batch Lookup',
    qualityReports: 'Quality Reports',

    // Profile
    personalInformation: 'Personal Information',
    businessDetails: 'Business Details',
    accountSettings: 'Account Settings',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    phoneNumber: 'Phone Number',
    address: 'Address',
    city: 'City',
    state: 'State',
    pincode: 'Pincode',
    farmName: 'Farm Name',
    farmSize: 'Farm Size',
    woolTypes: 'Wool Types',
    businessLicense: 'Business License',
    experience: 'Years of Experience',
    specialization: 'Specialization',
    bio: 'Bio / About',
    profileUpdated: 'Profile updated successfully!',

    // Inventory
    inventoryManagement: 'Inventory Management',
    warehouse: 'Warehouse',
    warehouses: 'Warehouses',
    addWarehouse: 'Add Warehouse',
    warehouseName: 'Warehouse Name',
    location: 'Location',
    capacity: 'Capacity',
    currentStock: 'Current Stock',
    stockValue: 'Stock Value',
    utilization: 'Utilization',
    addBatch: 'Add Batch',
    batchId: 'Batch ID',
    weight: 'Weight',
    value: 'Value',
    quality: 'Quality',
    lowStock: 'Low Stock',

    // Processing Services
    processingServices: 'Processing Services',
    browseServices: 'Browse Services',
    myBookings: 'My Bookings',
    bookService: 'Book Service',
    serviceProvider: 'Service Provider',
    pricePerKg: 'Price per kg',
    processingTime: 'Processing Time',
    totalBookings: 'Total Bookings',
    certifications: 'Certifications',

    // Education
    educationTraining: 'Education & Training',
    courses: 'Courses',
    myCourses: 'My Courses',
    certificates: 'Certificates',
    progress: 'Progress',
    startCourse: 'Start Course',
    completeCourse: 'Complete Course',
    loginToEnroll: 'Please login to enroll in courses',
    enrollSuccess: 'Successfully enrolled in course!',
    enrollFailed: 'Enrollment failed',
    educationTitle: 'Karnataka Wool Education & Training Center',
    educationSubtitle: 'Learn from experts and connect with wool producers across Karnataka',
    backToDashboard: 'Back to Dashboard',
    trainingResources: 'Training Resources',
    enrollNow: 'Enroll Now',
    producerDirectory: 'Producer Directory',
    searchPlaceholder: 'Search by name or expertise...',
    region: 'Region',
    allRegions: 'All Regions',
    allStates: 'All States',
    contact: 'Contact',
    registeredProducers: 'Registered Producers',
    trainingCourses: 'Training Courses',
    regionsCovered: 'Regions Covered',
    studentsEnrolled: 'Students Enrolled',

    // Product Catalog
    unknownFarmer: 'Unknown Farmer',
    wool: 'Wool',
    highQuality: 'High-quality',
    woolFrom: 'wool from',
    trustedFarmer: 'a trusted farmer',
    loginToAddToCart: 'Please log in to add items to cart',
    addedToCart: 'added to cart!',
    failedToAddToCart: 'Failed to add item to cart',
    productCatalogTitle: 'Karnataka Wool Products',
    items: 'items',
    viewCart: 'View Cart',
    filterSearch: 'Filter & Search Products',
    searchProducts: 'Search Products',
    woolType: 'Wool Type',
    allTypes: 'All Types',
    qualityGrade: 'Quality Grade',
    allGrades: 'All Grades',
    gradeAPlus: 'A+ Premium',
    gradeA: 'A Grade',
    gradeB: 'B Grade',
    minPrice: 'Min Price',
    sortBy: 'Sort By',
    newestFirst: 'Newest First',
    priceLowToHigh: 'Price: Low to High',
    priceHighToLow: 'Price: High to Low',
    highestRated: 'Highest Rated',
    availableProducts: 'Available Products',
    showing: 'Showing',
    of: 'of',
    grade: 'Grade',
    available: 'Available',
    addToCart: 'Add to Cart',
    outOfStock: 'Out of Stock',
    qualityDetails: 'Quality Details',
    noProductsFound: 'No Products Found',
    tryAdjustingFilters: 'Try adjusting your search filters or check back later for new products',
    clearAllFilters: 'Clear All Filters',

    // Inventory
    inventoryManagement: 'Inventory Management',
    inventorySubtitle: 'Manage warehouses and stock inventory',
    addWarehouse: 'Add Warehouse',
    totalWarehouses: 'Total Warehouses',
    totalStock: 'Total Stock',
    avgUtilization: 'Avg Utilization',
    noWarehousesFound: 'No warehouses found',
    createFirstWarehouse: 'Create your first warehouse to start managing inventory',
    lowStock: 'Low Stock',
    capacityUtilization: 'Capacity Utilization',
    stockValue: 'Stock Value',
    totalBatches: 'Total Batches',
    owner: 'Owner',
    addNewWarehouse: 'Add New Warehouse',
    warehouseName: 'Warehouse Name',
    location: 'Location',
    capacity: 'Capacity',
    description: 'Description',
    cancel: 'Cancel',
    createWarehouse: 'Create Warehouse',
    addBatchTo: 'Add Batch to',
    batchId: 'Batch ID',
    weight: 'Weight',
    value: 'Value',
    woolType: 'Wool Type',
    selectType: 'Select Type',
    fineWool: 'Fine Wool',
    mediumWool: 'Medium Wool',
    coarseWool: 'Coarse Wool',
    qualityGrade: 'Quality Grade',
    selectGrade: 'Select Grade',
    gradeAPremium: 'Grade A (Premium)',
    gradeBGood: 'Grade B (Good)',
    gradeCStandard: 'Grade C (Standard)',
    gradeDBelowStandard: 'Grade D (Below Standard)',
    addBatch: 'Add Batch',
    failedToCreateWarehouse: 'Failed to create warehouse',
    failedToAddBatch: 'Failed to add batch to warehouse',
    confirmDeleteWarehouse: 'Are you sure you want to delete this warehouse?',
    failedToDeleteWarehouse: 'Failed to delete warehouse',
    loadingInventory: 'Loading inventory data...',

    // Market Info
    marketInformation: 'Market Information',
    currentPrice: 'Current Price',
    priceChange: 'Price Change',
    volume: 'Volume',
    marketCap: 'Market Cap',
    industryNews: 'Industry News',

    // Common Actions
    viewDetails: 'View Details',
    downloadCertificate: 'Download Certificate',
    uploadImage: 'Upload Image',
    changePassword: 'Change Password',
    deactivateAccount: 'Deactivate Account',
    exportData: 'Export My Data',

    // Status
    pending: 'Pending',
    confirmed: 'Confirmed',
    inProgress: 'In Progress',
    completed: 'Completed',
    cancelled: 'Cancelled',
    approved: 'Approved',
    rejected: 'Rejected',

    // Messages
    noDataFound: 'No data found',
    errorLoading: 'Error loading data',
    successMessage: 'Operation completed successfully',
    errorMessage: 'An error occurred. Please try again.',
    confirmDelete: 'Are you sure you want to delete this?',

    // Roles
    farmer: 'Farmer',
    buyer: 'Buyer',
    government: 'Government',
    inspector: 'Inspector',

    // Marketplace
    loginToPurchase: 'Please log in to purchase',
    orderSuccess: 'Order placed successfully! Check your order history for details.',
    orderFailed: 'Failed to place order',
    loadingMarketplace: 'Loading marketplace...',
    marketplaceTitle: 'Karnataka Wool Marketplace',
    marketplaceSubtitle: 'Premium wool batches from verified farmers across Karnataka',
    availableBatches: 'Available Batches',
    allVerified: 'All Verified',
    yourBatch: 'Your Batch',
    type: 'Type',
    total: 'Total',
    purchaseBatch: 'Purchase Batch',
    noBatchesFound: 'No Batches Available',
    checkBackLater: 'Check back later for new premium wool batches from Karnataka farmers',
  },

  kn: { // Kannada
    // Common
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    save: 'ಉಳಿಸಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    delete: 'ಅಳಿಸಿ',
    edit: 'ಸಂಪಾದಿಸಿ',
    view: 'ನೋಡಿ',
    search: 'ಹುಡುಕಿ',
    filter: 'ಫಿಲ್ಟರ್',
    export: 'ರಫ್ತು ಮಾಡಿ',
    import: 'ಆಮದು ಮಾಡಿ',
    yes: 'ಹೌದು',
    no: 'ಇಲ್ಲ',
    close: 'ಮುಚ್ಚಿ',
    submit: 'ಸಲ್ಲಿಸಿ',

    // Navigation
    home: 'ಮುಖಪುಟ',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    products: 'ಉತ್ಪನ್ನಗಳು',
    marketplace: 'ಮಾರುಕಟ್ಟೆ',
    inventory: 'ದಾಸ್ತಾನು',
    processing: 'ಪ್ರಕ್ರಿಯೆ ಸೇವೆಗಳು',
    education: 'ಶಿಕ್ಷಣ ಮತ್ತು ತರಬೇತಿ',
    profile: 'ಪ್ರೊಫೈಲ್',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    logout: 'ಲಾಗ್ ಔಟ್',
    login: 'ಲಾಗಿನ್',

    // Dashboard
    totalBatches: 'ಒಟ್ಟು ಬ್ಯಾಚ್‌ಗಳು',
    totalOrders: 'ಒಟ್ಟು ಆದೇಶಗಳು',
    totalSales: 'ಒಟ್ಟು ಮಾರಾಟ',
    rating: 'ರೇಟಿಂಗ್',
    reviews: 'ವಿಮರ್ಶೆಗಳು',
    approvedSales: 'ಅನುಮೋದಿತ ಮಾರಾಟ',
    totalRevenue: 'ಒಟ್ಟು ಆದಾಯ',
    delivered: 'ವಿತರಿಸಲಾಗಿದೆ',
    inTransit: 'ಸಾಗಣೆಯಲ್ಲಿದೆ',
    totalSpent: 'ಒಟ್ಟು ಖರ್ಚು',
    applications: 'ಅರ್ಜಿಗಳು',
    totalValue: 'ಒಟ್ಟು ಮೌಲ್ಯ',
    pendingInspection: 'ತಪಾಸಣೆ ಬಾಕಿ ಇದೆ',
    inspectedToday: 'ಇಂದು ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    gradeABatches: 'ಗ್ರೇಡ್ A+ ಬ್ಯಾಚ್‌ಗಳು',
    totalInspections: 'ಒಟ್ಟು ತಪಾಸಣೆಗಳು',
    quickActions: 'ತ್ವರಿತ ಕ್ರಮಗಳು',
    sales: 'ಮಾರಾಟ',
    training: 'ತರಬೇತಿ',
    shopNow: 'ಈಗ ಖರೀದಿಸಿ',
    cart: 'ಕಾರ್ಟ್',
    trackOrders: 'ಆದೇಶಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    adminPanel: 'ನಿರ್ವಾಹक ಫಲಕ',
    marketInfo: 'ಮಾರುಕಟ್ಟೆ ಮಾಹಿತಿ',
    qualityAssessment: 'ಗುಣಮಟ್ಟದ ಮೌಲ್ಯಮಾಪನ',
    batchLookup: 'ಬ್ಯಾಚ್ ಹುಡುಕಾಟ',
    qualityReports: 'ಗುಣಮಟ್ಟದ ವರದಿಗಳು',

    // Profile
    personalInformation: 'ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ',
    businessDetails: 'ವ್ಯಾಪಾರ ವಿವರಗಳು',
    accountSettings: 'ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    emailAddress: 'ಇಮೇಲ್ ವಿಳಾಸ',
    phoneNumber: 'ದೂರವಾಣಿ ಸಂಖ್ಯೆ',
    address: 'ವಿಳಾಸ',
    city: 'ನಗರ',
    state: 'ರಾಜ್ಯ',
    pincode: 'ಪಿನ್‌ಕೋಡ್',
    farmName: 'ಫಾರ್ಮ್ ಹೆಸರು',
    farmSize: 'ಫಾರ್ಮ್ ಗಾತ್ರ',
    woolTypes: 'ಉಣ್ಣೆ ವಿಧಗಳು',
    businessLicense: 'ವ್ಯಾಪಾರ ಪರವಾನಗಿ',
    experience: 'ಅನುಭವದ ವರ್ಷಗಳು',
    specialization: 'ವಿಶೇಷತೆ',
    bio: 'ಪರಿಚಯ',
    profileUpdated: 'ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!',

    // Inventory
    inventoryManagement: 'ದಾಸ್ತಾನು ನಿರ್ವಹಣೆ',
    warehouse: 'ಗೋದಾಮು',
    warehouses: 'ಗೋದಾಮುಗಳು',
    addWarehouse: 'ಗೋದಾಮು ಸೇರಿಸಿ',
    warehouseName: 'ಗೋದಾಮಿನ ಹೆಸರು',
    location: 'ಸ್ಥಳ',
    capacity: 'ಸಾಮರ್ಥ್ಯ',
    currentStock: 'ಪ್ರಸ್ತುತ ಸ್ಟಾಕ್',
    stockValue: 'ಸ್ಟಾಕ್ ಮೌಲ್ಯ',
    utilization: 'ಬಳಕೆ',
    addBatch: 'ಬ್ಯಾಚ್ ಸೇರಿಸಿ',
    batchId: 'ಬ್ಯಾಚ್ ಐಡಿ',
    weight: 'ತೂಕ',
    value: 'ಮೌಲ್ಯ',
    quality: 'ಗುಣಮಟ್ಟ',
    lowStock: 'ಕಡಿಮೆ ಸ್ಟಾಕ್',

    // Processing Services
    processingServices: 'ಪ್ರಕ್ರಿಯೆ ಸೇವೆಗಳು',
    browseServices: 'ಸೇವೆಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ',
    myBookings: 'ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು',
    bookService: 'ಸೇವೆಯನ್ನು ಬುಕ್ ಮಾಡಿ',
    serviceProvider: 'ಸೇವಾ ಪೂರೈಕೆದಾರರ',
    pricePerKg: 'ಪ್ರತಿ ಕೆಜಿ ಬೆಲೆ',
    processingTime: 'ಪ್ರಕ್ರಿಯೆ ಸಮಯ',
    totalBookings: 'ಒಟ್ಟು ಬುಕಿಂಗ್‌ಗಳು',
    certifications: 'ಪ್ರಮಾಣಪತ್ರಗಳು',

    // Education
    educationTraining: 'ಶಿಕ್ಷಣ ಮತ್ತು ತರಬೇತಿ',
    courses: 'ಕೋರ್ಸುಗಳು',
    myCourses: 'ನನ್ನ ಕೋರ್ಸುಗಳು',
    certificates: 'ಪ್ರಮಾಣಪತ್ರಗಳು',
    progress: 'ಪ್ರಗತಿ',
    startCourse: 'ಕೋರ್ಸ್ ಪ್ರಾರಂಭಿಸಿ',
    completeCourse: 'ಕೋರ್ಸ್ ಪೂರ್ಣಗೊಳಿಸಿ',
    loginToEnroll: 'ಕೋರ್ಸ್‌ಗಳಿಗೆ ನೋಂದಾಯಿಸಲು ದಯವಿಟ್ಟು ಲಾಗಿನ್ ಮಾಡಿ',
    enrollSuccess: 'ಕೋರ್ಸ್‌ಗೆ ಯಶಸ್ವಿಯಾಗಿ ನೋಂದಾಯಿಸಲಾಗಿದೆ!',
    enrollFailed: 'ನೋಂದಣಿ ವಿಫಲವಾಗಿದೆ',
    educationTitle: 'ಕರ್ನಾಟಕ ಉಣ್ಣೆ ಶಿಕ್ಷಣ ಮತ್ತು ತರಬೇತಿ ಕೇಂದ್ರ',
    educationSubtitle: 'ತಜ್ಞರಿಂದ ಕಲಿಯಿರಿ ಮತ್ತು ಕರ್ನಾಟಕದಾದ್ಯಂತ ಉಣ್ಣೆ ಉತ್ಪಾದಕರೊಂದಿಗೆ ಸಂಪರ್ಕ ಸಾಧಿಸಿ',
    backToDashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂತಿರುಗಿ',
    trainingResources: 'ತರಬೇತಿ ಸಂಪನ್ಮೂಲಗಳು',
    enrollNow: 'ಈಗ ನೋಂದಾಯಿಸಿ',
    producerDirectory: 'ಉತ್ಪಾದಕರ ಡೈರೆಕ್ಟರಿ',
    searchPlaceholder: 'ಹೆಸರು ಅಥವಾ ಪರಿಣತಿಯ ಮೂಲಕ ಹುಡುಕಿ...',
    region: 'ಪ್ರದೇಶ',
    allRegions: 'ಎಲ್ಲಾ ಪ್ರದೇಶಗಳು',
    allStates: 'ಎಲ್ಲಾ ರಾಜ್ಯಗಳು',
    contact: 'ಸಂಪರ್ಕಿಸಿ',
    registeredProducers: 'ನೋಂದಾಯಿತ ಉತ್ಪಾದಕರು',
    trainingCourses: 'ತರಬೇತಿ ಕೋರ್ಸ್‌ಗಳು',
    regionsCovered: 'ಒಳಗೊಂಡಿರುವ ಪ್ರದೇಶಗಳು',
    studentsEnrolled: 'ನೋಂದಾಯಿತ ವಿದ್ಯಾರ್ಥಿಗಳು',

    // Product Catalog
    unknownFarmer: 'ಅಪರಿಚಿತ ರೈತ',
    wool: 'ಉಣ್ಣೆ',
    highQuality: 'ಉತ್ತಮ ಗುಣಮಟ್ಟದ',
    woolFrom: 'ಉಣ್ಣೆ ಇವರಿಂದ',
    trustedFarmer: 'ಒಬ್ಬ ವಿಶ್ವಾಸಾರ್ಹ ರೈತ',
    loginToAddToCart: 'ಕಾರ್ಟ್‌ಗೆ ಐಟಂಗಳನ್ನು ಸೇರಿಸಲು ದಯವಿಟ್ಟು ಲಾಗಿನ್ ಮಾಡಿ',
    addedToCart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಲಾಗಿದೆ!',
    failedToAddToCart: 'ಕಾರ್ಟ್‌ಗೆ ಐಟಂ ಸೇರಿಸಲು ವಿಫಲವಾಗಿದೆ',
    productCatalogTitle: 'ಕರ್ನಾಟಕ ಉಣ್ಣೆ ಉತ್ಪನ್ನಗಳು',
    items: 'ಐಟಂಗಳು',
    viewCart: 'ಕಾರ್ಟ್ ವೀಕ್ಷಿಸಿ',
    filterSearch: 'ಉತ್ಪನ್ನಗಳನ್ನು ಫಿಲ್ಟರ್ ಮಾಡಿ ಮತ್ತು ಹುಡುಕಿ',
    searchProducts: 'ಉತ್ಪನ್ನಗಳನ್ನು ಹುಡುಕಿ',
    woolType: 'ಉಣ್ಣೆ ವಿಧ',
    allTypes: 'ಎಲ್ಲಾ ವಿಧಗಳು',
    qualityGrade: 'ಗುಣಮಟ್ಟದ ಶ್ರೇಣಿ',
    allGrades: 'ಎಲ್ಲಾ ಶ್ರೇಣಿಗಳು',
    gradeAPlus: 'A+ ಪ್ರೀಮಿಯಂ',
    gradeA: 'A ಶ್ರೇಣಿ',
    gradeB: 'B ಶ್ರೇಣಿ',
    minPrice: 'ಕನಿಷ್ಠ ಬೆಲೆ',
    sortBy: 'ಇದರಂತೆ ವಿಂಗಡಿಸಿ',
    newestFirst: 'ಹೊಸದು ಮೊದಲು',
    priceLowToHigh: 'ಬೆಲೆ: ಕಡಿಮೆಯಿಂದ ಹೆಚ್ಚಿಗೆ',
    priceHighToLow: 'ಬೆಲೆ: ಹೆಚ್ಚಿನಿಂದ ಕಡಿಮೆಗೆ',
    highestRated: 'ಅತ್ಯಧಿಕ ರೇಟ್ ಮಾಡಲಾಗಿದೆ',
    availableProducts: 'ಲಭ್ಯವಿರುವ ಉತ್ಪನ್ನಗಳು',
    showing: 'ತೋರಿಸಲಾಗುತ್ತಿದೆ',
    of: 'ರ',
    grade: 'ಶ್ರೇಣಿ',
    available: 'ಲಭ್ಯವಿದೆ',
    addToCart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ',
    outOfStock: 'ಸ್ಟಾಕ್ ಖಾಲಿಯಾಗಿದೆ',
    qualityDetails: 'ಗುಣಮಟ್ಟದ ವಿವರಗಳು',
    noProductsFound: 'ಯಾವುದೇ ಉತ್ಪನ್ನಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    tryAdjustingFilters: 'ನಿಮ್ಮ ಹುಡುಕಾಟ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಹೊಂದಿಸಲು ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಹೊಸ ಉತ್ಪನ್ನಗಳಿಗಾಗಿ ನಂತರ ಪರಿಶೀಲಿಸಿ',
    clearAllFilters: 'ಎಲ್ಲಾ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ',

    // Inventory
    inventoryManagement: 'ದಾಸ್ತಾನು ನಿರ್ವಹಣೆ',
    inventorySubtitle: 'ಗೋದಾಮುಗಳು ಮತ್ತು ಸ್ಟಾಕ್ ದಾಸ್ತಾನು ನಿರ್ವಹಿಸಿ',
    addWarehouse: 'ಗೋದಾಮನ್ನು ಸೇರಿಸಿ',
    totalWarehouses: 'ಒಟ್ಟು ಗೋದಾಮುಗಳು',
    totalStock: 'ಒಟ್ಟು ಸ್ಟಾಕ್',
    avgUtilization: 'ಸರಾಸರಿ ಬಳಕೆ',
    noWarehousesFound: 'ಯಾವುದೇ ಗೋದಾಮುಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    createFirstWarehouse: 'ದಾಸ್ತಾನು ನಿರ್ವಹಣೆಯನ್ನು ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಮೊದಲ ಗೋದಾಮನ್ನು ರಚಿಸಿ',
    lowStock: 'ಕಡಿಮೆ ಸ್ಟಾಕ್',
    capacityUtilization: 'ಸಾಮರ್ಥ್ಯ ಬಳಕೆ',
    stockValue: 'ಸ್ಟಾಕ್ ಮೌಲ್ಯ',
    totalBatches: 'ಒಟ್ಟು ಬ್ಯಾಚ್‌ಗಳು',
    owner: 'ಮಾಲೀಕರು',
    addNewWarehouse: 'ಹೊಸ ಗೋದಾಮನ್ನು ಸೇರಿಸಿ',
    warehouseName: 'ಗೋದಾಮಿನ ಹೆಸರು',
    location: 'ಸ್ಥಳ',
    capacity: 'ಸಾಮರ್ಥ್ಯ',
    description: 'ವಿವರಣೆ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    createWarehouse: 'ಗೋದಾಮನ್ನು ರಚಿಸಿ',
    addBatchTo: 'ಇದಕ್ಕೆ ಬ್ಯಾಚ್ ಸೇರಿಸಿ',
    batchId: 'ಬ್ಯಾಚ್ ಐಡಿ',
    weight: 'ತೂಕ',
    value: 'ಮೌಲ್ಯ',
    woolType: 'ಉಣ್ಣೆ ವಿಧ',
    selectType: 'ವಿಧವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    fineWool: 'ಉತ್ತಮ ಉಣ್ಣೆ',
    mediumWool: 'ಮಧ್ಯಮ ಉಣ್ಣೆ',
    coarseWool: 'ದಪ್ಪ ಉಣ್ಣೆ',
    qualityGrade: 'ಗುಣಮಟ್ಟದ ಶ್ರೇಣಿ',
    selectGrade: 'ಶ್ರೇಣಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    gradeAPremium: 'ಶ್ರೇಣಿ A (ಪ್ರೀಮಿಯಂ)',
    gradeBGood: 'ಶ್ರೇಣಿ B (ಉತ್ತಮ)',
    gradeCStandard: 'ಶ್ರೇಣಿ C (ಸಾಮಾನ್ಯ)',
    gradeDBelowStandard: 'ಶ್ರೇಣಿ D (ಸಾಮಾನ್ಯಕ್ಕಿಂತ ಕಡಿಮೆ)',
    addBatch: 'ಬ್ಯಾಚ್ ಸೇರಿಸಿ',
    failedToCreateWarehouse: 'ಗೋದಾಮನ್ನು ರಚಿಸಲು ವಿಫಲವಾಗಿದೆ',
    failedToAddBatch: 'ಗೋದಾಮಿಗೆ ಬ್ಯಾಚ್ ಸೇರಿಸಲು ವಿಫಲವಾಗಿದೆ',
    confirmDeleteWarehouse: 'ಈ ಗೋದಾಮನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿದ್ದೀರಾ?',
    failedToDeleteWarehouse: 'ಗೋದಾಮನ್ನು ಅಳಿಸಲು ವಿಫಲವಾಗಿದೆ',
    loadingInventory: 'ದಾಸ್ತಾನು ಡೇಟಾ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',

    // Market Info
    marketInformation: 'ಮಾರುಕಟ್ಟೆ ಮಾಹಿತಿ',
    currentPrice: 'ಪ್ರಸ್ತುತ ಬೆಲೆ',
    priceChange: 'ಬೆಲೆ ಬದಲಾವಣೆ',
    volume: 'ಪ್ರಮಾಣ',
    marketCap: 'ಮಾರುಕಟ್ಟೆ ಬಂಡವಾಳ',
    industryNews: 'ಉದ್ಯಮ ಸುದ್ದಿ',

    // Roles
    farmer: 'ರೈತ',
    buyer: 'ಖರೀದಿದಾರ',
    government: 'ಸರ್ಕಾರ',
    inspector: 'ತಪಾಸಣಾಧಿಕಾರಿ',

    // Marketplace
    loginToPurchase: 'ಖರೀದಿಸಲು ದಯವಿಟ್ಟು ಲಾಗಿನ್ ಮಾಡಿ',
    orderSuccess: 'ಆದೇಶವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಇರಿಸಲಾಗಿದೆ! ವಿವರಗಳಿಗಾಗಿ ನಿಮ್ಮ ಆದೇಶ ಇತಿಹಾಸವನ್ನು ಪರಿಶೀಲಿಸಿ.',
    orderFailed: 'ಆದೇಶವನ್ನು ಇರಿಸಲು ವಿಫಲವಾಗಿದೆ',
    loadingMarketplace: 'ಮಾರುಕಟ್ಟೆಯನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    marketplaceTitle: 'ಕರ್ನಾಟಕ ಉಣ್ಣೆ ಮಾರುಕಟ್ಟೆ',
    marketplaceSubtitle: 'ಕರ್ನಾಟಕದಾದ್ಯಂತ ಪರಿಶೀಲಿಸಿದ ರೈತರಿಂದ ಪ್ರೀಮಿಯಂ ಉಣ್ಣೆ ಬ್ಯಾಚ್‌ಗಳು',
    availableBatches: 'ಲಭ್ಯವಿರುವ ಬ್ಯಾಚ್‌ಗಳು',
    allVerified: 'ಎಲ್ಲವನ್ನೂ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    yourBatch: 'ನಿಮ್ಮ ಬ್ಯಾಚ್',
    type: 'ವಿಧ',
    total: 'ಒಟ್ಟು',
    purchaseBatch: 'ಬ್ಯಾಚ್ ಖರೀದಿಸಿ',
    noBatchesFound: 'ಯಾವುದೇ ಬ್ಯಾಚ್‌ಗಳು ಲಭ್ಯವಿಲ್ಲ',
    checkBackLater: 'ಕರ್ನಾಟಕ ರೈತರಿಂದ ಹೊಸ ಪ್ರೀಮಿಯಂ ಉಣ್ಣೆ ಬ್ಯಾಚ್‌ಗಳಿಗಾಗಿ ನಂತರ ಪರಿಶೀಲಿಸಿ',
  },

  hi: { // Hindi
    // Common
    loading: 'लोड हो रहा है...',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    view: 'देखें',
    search: 'खोजें',
    filter: 'फ़िल्टर',
    export: 'निर्यात',
    import: 'आयात',
    yes: 'हां',
    no: 'नहीं',
    close: 'बंद करें',
    submit: 'जमा करें',

    // Navigation
    home: 'होम',
    dashboard: 'डैशबोर्ड',
    products: 'उत्पाद',
    marketplace: 'बाज़ार',
    inventory: 'इन्वेंटरी',
    processing: 'प्रोसेसिंग सेवाएं',
    education: 'शिक्षा और प्रशिक्षण',
    profile: 'प्रोफ़ाइल',
    settings: 'सेटिंग्स',
    logout: 'लॉग आउट',
    login: 'लॉगिन',

    // Dashboard
    totalBatches: 'कुल बैच',
    totalOrders: 'कुल ऑर्डर',
    totalSales: 'कुल बिक्री',
    rating: 'रेटिंग',
    reviews: 'समीक्षाएं',
    approvedSales: 'स्वीकृत बिक्री',
    totalRevenue: 'कुल राजस्व',
    delivered: 'वितरित',
    inTransit: 'रास्ते में',
    totalSpent: 'कुल खर्च',
    applications: 'आवेदन',
    totalValue: 'कुल मूल्य',
    pendingInspection: 'निरीक्षण लंबित',
    inspectedToday: 'आज निरीक्षण किया गया',
    gradeABatches: 'ग्रेड A+ बैच',
    totalInspections: 'कुल निरीक्षण',
    quickActions: 'त्वरित कार्रवाई',
    sales: 'बिक्री',
    training: 'प्रशिक्षण',
    shopNow: 'अभी खरीदें',
    cart: 'कार्ट',
    trackOrders: 'ऑर्डर ट्रैक करें',
    adminPanel: 'एडमिन पैनल',
    marketInfo: 'बाजार की जानकारी',
    qualityAssessment: 'गुणवत्ता मूल्यांकन',
    batchLookup: 'बैच खोजें',
    qualityReports: 'गुणवत्ता रिपोर्ट',

    // Profile
    personalInformation: 'व्यक्तिगत जानकारी',
    businessDetails: 'व्यापार विवरण',
    accountSettings: 'खाता सेटिंग्स',
    fullName: 'पूरा नाम',
    emailAddress: 'ईमेल पता',
    phoneNumber: 'फोन नंबर',
    address: 'पता',
    city: 'शहर',
    state: 'राज्य',
    pincode: 'पिनकोड',
    farmName: 'फार्म का नाम',
    farmSize: 'फार्म का आकार',
    woolTypes: 'ऊन के प्रकार',
    businessLicense: 'व्यापार लाइसेंस',
    experience: 'अनुभव के वर्ष',
    specialization: 'विशेषज्ञता',
    bio: 'परिचय',
    profileUpdated: 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!',

    // Education
    educationTraining: 'शिक्षा और प्रशिक्षण',
    courses: 'पाठ्यक्रम',
    myCourses: 'मेरे पाठ्यक्रम',
    certificates: 'प्रमाणपत्र',
    progress: 'प्रगति',
    startCourse: 'पाठ्यक्रम शुरू करें',
    completeCourse: 'पाठ्यक्रम पूरा करें',
    loginToEnroll: 'पाठ्यक्रमों में नामांकन के लिए कृपया लॉगिन करें',
    enrollSuccess: 'पाठ्यक्रम में सफलतापूर्वक नामांकन किया गया!',
    enrollFailed: 'नामांकन विफल',
    educationTitle: 'कर्नाटक ऊन शिक्षा और प्रशिक्षण केंद्र',
    educationSubtitle: 'विशेषज्ञों से सीखें और कर्नाटक भर के ऊन उत्पादकों से जुड़ें',
    backToDashboard: 'डैशबोर्ड पर वापस जाएं',
    trainingResources: 'प्रशिक्षण संसाधन',
    enrollNow: 'अभी नामांकन करें',
    producerDirectory: 'उत्पादक निर्देशिका',
    searchPlaceholder: 'नाम या विशेषज्ञता से खोजें...',
    region: 'क्षेत्र',
    allRegions: 'सभी क्षेत्र',
    allStates: 'सभी राज्य',
    contact: 'संपर्क करें',
    registeredProducers: 'पंजीकृत उत्पादक',
    trainingCourses: 'प्रशिक्षण पाठ्यक्रम',
    regionsCovered: 'कवर किए गए क्षेत्र',
    studentsEnrolled: 'नामांकित छात्र',

    // Product Catalog
    unknownFarmer: 'अज्ञात किसान',
    wool: 'ऊन',
    highQuality: 'उच्च गुणवत्ता',
    woolFrom: 'से ऊन',
    trustedFarmer: 'एक विश्वसनीय किसान',
    loginToAddToCart: 'कार्ट में आइटम जोड़ने के लिए कृपया लॉगिन करें',
    addedToCart: 'कार्ट में जोड़ा गया!',
    failedToAddToCart: 'कार्ट में आइटम जोड़ने में विफल',
    productCatalogTitle: 'कर्नाटक ऊन उत्पाद',
    items: 'आइटम',
    viewCart: 'कार्ट देखें',
    filterSearch: 'उत्पादों को फ़िल्टर और खोजें',
    searchProducts: 'उत्पाद खोजें',
    woolType: 'ऊन का प्रकार',
    allTypes: 'सभी प्रकार',
    qualityGrade: 'गुणवत्ता ग्रेड',
    allGrades: 'सभी ग्रेड',
    gradeAPlus: 'A+ प्रीमियम',
    gradeA: 'A ग्रेड',
    gradeB: 'B ग्रेड',
    minPrice: 'न्यूनतम मूल्य',
    sortBy: 'क्रमबद्ध करें',
    newestFirst: 'नया पहले',
    priceLowToHigh: 'मूल्य: कम से ज्यादा',
    priceHighToLow: 'मूल्य: ज्यादा से कम',
    highestRated: 'उच्चतम रेटेड',
    availableProducts: 'उपलब्ध उत्पाद',
    showing: 'दिखा रहा है',
    of: 'का',
    grade: 'ग्रेड',
    available: 'उपलब्ध',
    addToCart: 'कार्ट में जोड़ें',
    outOfStock: 'स्टॉक में नहीं',
    qualityDetails: 'गुणवत्ता विवरण',
    noProductsFound: 'कोई उत्पाद नहीं मिला',
    tryAdjustingFilters: 'अपनी खोज फ़िल्टर समायोजित करने का प्रयास करें या नए उत्पादों के लिए बाद में देखें',
    clearAllFilters: 'सभी फ़िल्टर साफ़ करें',

    // Inventory
    inventoryManagement: 'इन्वेंटरी प्रबंधन',
    inventorySubtitle: 'गोदामों और स्टॉक इन्वेंटरी का प्रबंधन करें',
    addWarehouse: 'गोदाम जोड़ें',
    totalWarehouses: 'कुल गोदाम',
    totalStock: 'कुल स्टॉक',
    avgUtilization: 'औसत उपयोग',
    noWarehousesFound: 'कोई गोदाम नहीं मिला',
    createFirstWarehouse: 'इन्वेंटरी प्रबंधन शुरू करने के लिए अपना पहला गोदाम बनाएं',
    lowStock: 'कम स्टॉक',
    capacityUtilization: 'क्षमता उपयोग',
    stockValue: 'स्टॉक मूल्य',
    totalBatches: 'कुल बैच',
    owner: 'मालिक',
    addNewWarehouse: 'नया गोदाम जोड़ें',
    warehouseName: 'गोदाम का नाम',
    location: 'स्थान',
    capacity: 'क्षमता',
    description: 'विवरण',
    cancel: 'रद्द करें',
    createWarehouse: 'गोदाम बनाएं',
    addBatchTo: 'में बैच जोड़ें',
    batchId: 'बैच आईडी',
    weight: 'वजन',
    value: 'मूल्य',
    woolType: 'ऊन का प्रकार',
    selectType: 'प्रकार चुनें',
    fineWool: 'महीन ऊन',
    mediumWool: 'मध्यम ऊन',
    coarseWool: 'मोटा ऊन',
    qualityGrade: 'गुणवत्ता ग्रेड',
    selectGrade: 'ग्रेड चुनें',
    gradeAPremium: 'ग्रेड A (प्रीमियम)',
    gradeBGood: 'ग्रेड B (अच्छा)',
    gradeCStandard: 'ग्रेड C (मानक)',
    gradeDBelowStandard: 'ग्रेड D (मानक से नीचे)',
    addBatch: 'बैच जोड़ें',
    failedToCreateWarehouse: 'गोदाम बनाने में विफल',
    failedToAddBatch: 'गोदाम में बैच जोड़ने में विफल',
    confirmDeleteWarehouse: 'क्या आप वाकई इस गोदाम को हटाना चाहते हैं?',
    failedToDeleteWarehouse: 'गोदाम हटाने में विफल',
    loadingInventory: 'इन्वेंटरी डेटा लोड हो रहा है...',

    farmer: 'किसान',
    buyer: 'खरीदार',
    government: 'सरकार',
    inspector: 'निरीक्षक',

    // Marketplace
    loginToPurchase: 'खरीदने के लिए कृपया लॉगिन करें',
    orderSuccess: 'ऑर्डर सफलतापूर्वक दिया गया! विवरण के लिए अपना ऑर्डर इतिहास देखें।',
    orderFailed: 'ऑर्डर देने में विफल',
    loadingMarketplace: 'बाज़ार लोड हो रहा है...',
    marketplaceTitle: 'कर्नाटक ऊन बाज़ार',
    marketplaceSubtitle: 'कर्नाटक भर के सत्यापित किसानों से प्रीमियम ऊन बैच',
    availableBatches: 'उपलब्ध बैच',
    allVerified: 'सभी सत्यापित',
    yourBatch: 'आपका बैच',
    type: 'प्रकार',
    total: 'कुल',
    purchaseBatch: 'बैच खरीदें',
    noBatchesFound: 'कोई बैच उपलब्ध नहीं',
    checkBackLater: 'कर्नाटक के किसानों से नए प्रीमियम ऊन बैचों के लिए बाद में देखें',
  },

  ta: { // Tamil
    loading: 'ஏற்றுகிறது...',
    save: 'சேமி',
    cancel: 'ரத்து',
    delete: 'நீக்கு',
    edit: 'திருத்து',
    view: 'பார்',
    search: 'தேடு',
    home: 'முகப்பு',
    dashboard: 'டாஷ்போர்டு',
    products: 'தயாரிப்புகள்',
    marketplace: 'சந்தை',
    inventory: 'இருப்பு',
    processing: 'செயலாக்க சேவைகள்',
    education: 'கல்வி மற்றும் பயிற்சி',
    profile: 'சுயவிவரம்',
    settings: 'அமைப்புகள்',
    logout: 'வெளியேறு',
    login: 'உள்நுழை',
    farmer: 'விவசாயி',
    buyer: 'வாங்குபவர்',
    government: 'அரசு',
    inspector: 'ஆய்வாளர்',

    // Marketplace
    loginToPurchase: 'வாங்க உள்நுழையவும்',
    orderSuccess: 'ஆர்டர் வெற்றிகரமாக வைக்கப்பட்டது!',
    orderFailed: 'ஆர்டர் செய்ய முடியவில்லை',
    loadingMarketplace: 'சந்தை ஏற்றப்படுகிறது...',
    marketplaceTitle: 'கர்நாடக கம்பளி சந்தை',
    marketplaceSubtitle: 'கர்நாடகா முழுவதும் சரிபார்க்கப்பட்ட விவசாயிகளிடமிருந்து பிரீமியம் கம்பளி',
    availableBatches: 'கிடைக்கும் தொகுதிகள்',
    allVerified: 'அனைத்தும் சரிபார்க்கப்பட்டது',
    yourBatch: 'உங்கள் தொகுதி',
    type: 'வகை',
    total: 'மொத்தம்',
    purchaseBatch: 'தொகுதியை வாங்கவும்',
    noBatchesFound: 'தொகுதிகள் எதுவும் இல்லை',
    checkBackLater: 'பின்னர் மீண்டும் சரிபார்க்கவும்',

    // Dashboard
    totalBatches: 'மொத்த தொகுதிகள்',
    totalOrders: 'மொத்த ஆர்டர்கள்',
    totalSales: 'மொத்த விற்பனை',
    rating: 'மதிப்பீடு',
    reviews: 'விமர்சனங்கள்',
    approvedSales: 'அங்கீகரிக்கப்பட்ட விற்பனை',
    totalRevenue: 'மொத்த வருவாய்',
    delivered: 'வழங்கப்பட்டது',
    inTransit: 'வழியில்',
    totalSpent: 'மொத்த செலவு',
    applications: 'விண்ணப்பங்கள்',
    totalValue: 'மொத்த மதிப்பு',
    pendingInspection: 'ஆய்வு நிலுவையில் உள்ளது',
    inspectedToday: 'இன்று ஆய்வு செய்யப்பட்டது',
    gradeABatches: 'தரம் A+ தொகுதிகள்',
    totalInspections: 'மொத்த ஆய்வுகள்',
    quickActions: 'விரைவான செயல்கள்',
    sales: 'விற்பனை',
    training: 'பயிற்சி',
    shopNow: 'இப்போது வாங்கவும்',
    cart: 'வண்டி',
    trackOrders: 'ஆர்டர்களைக் கண்காணிக்கவும்',
    adminPanel: 'நிர்வாகக் குழு',
    marketInfo: 'சந்தை தகவல்',
    qualityAssessment: 'தர மதிப்பீடு',
    batchLookup: 'தொகுதி தேடல்',
    qualityReports: 'தர அறிக்கைகள்',

    // Profile
    personalInformation: 'தனிப்பட்ட தகவல்',
    businessDetails: 'வணிக விவரங்கள்',
    accountSettings: 'கணக்கு அமைப்புகள்',
    fullName: 'முழு பெயர்',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    phoneNumber: 'தொலைபேசி எண்',
    address: 'முகவரி',
    city: 'நகரம்',
    state: 'மாநிலம்',
    pincode: 'அஞ்சல் குறியீடு',
    farmName: 'பண்ணை பெயர்',
    farmSize: 'பண்ணை அளவு',
    woolTypes: 'கம்பளி வகைகள்',
    businessLicense: 'வணிக உரிமம்',
    experience: 'அனுபவ ஆண்டுகள்',
    specialization: 'சிறப்பு',
    bio: 'சுயவிவரம்',
    profileUpdated: 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
    changePassword: 'கடவுச்சொல்லை மாற்றவும்',
    exportData: 'தரவை ஏற்றுமதி செய்',
    deactivateAccount: 'கணக்கை முடக்கு',

    // Education
    educationTraining: 'கல்வி மற்றும் பயிற்சி',
    courses: 'படிப்புகள்',
    myCourses: 'எனது படிப்புகள்',
    certificates: 'சான்றிதழ்கள்',
    progress: 'முன்னேற்றம்',
    startCourse: 'படிப்பைத் தொடங்குங்கள்',
    completeCourse: 'படிப்பை முடிக்கவும்',
    loginToEnroll: 'படிப்புகளில் சேர உள்நுழையவும்',
    enrollSuccess: 'படிப்பில் வெற்றிகரமாக சேர்க்கப்பட்டது!',
    enrollFailed: 'சேர்க்கை தோல்வியடைந்தது',
    educationTitle: 'கர்நாடக கம்பளி கல்வி மற்றும் பயிற்சி மையம்',
    educationSubtitle: 'நிபுணர்களிடமிருந்து கற்றுக்கொள்ளுங்கள்',
    backToDashboard: 'டாஷ்போர்டுக்குத் திரும்பு',
    trainingResources: 'பயிற்சி வளங்கள்',
    enrollNow: 'இப்போது சேரவும்',
    producerDirectory: 'உற்பத்தியாளர் அடைவு',
    searchPlaceholder: 'பெயர் அல்லது நிபுணத்துவம் மூலம் தேடவும்...',
    region: 'பகுதி',
    allRegions: 'அனைத்து பகுதிகளும்',
    allStates: 'அனைத்து மாநிலங்களும்',
    contact: 'தொடர்பு',
    registeredProducers: 'பதிவு செய்யப்பட்ட உற்பத்தியாளர்கள்',
    trainingCourses: 'பயிற்சி படிப்புகள்',
    regionsCovered: 'உள்ளடக்கிய பகுதிகள்',
    studentsEnrolled: 'சேர்ந்த மாணவர்கள்',

    // Product Catalog
    unknownFarmer: 'தெரியாத விவசாயி',
    wool: 'கம்பளி',
    highQuality: 'உயர்தர',
    woolFrom: 'இருந்து கம்பளி',
    trustedFarmer: 'நம்பகமான விவசாயி',
    loginToAddToCart: 'வண்டியில் பொருட்களைச் சேர்க்க உள்நுழையவும்',
    addedToCart: 'வண்டியில் சேர்க்கப்பட்டது!',
    failedToAddToCart: 'வண்டியில் சேர்க்க முடியவில்லை',
    productCatalogTitle: 'கர்நாடக கம்பளி தயாரிப்புகள்',
    items: 'பொருட்கள்',
    viewCart: 'வண்டியைப் பார்',
    filterSearch: 'வடிகட்டி மற்றும் தேடல்',
    searchProducts: 'தயாரிப்புகளைத் தேடுங்கள்',
    woolType: 'கம்பளி வகை',
    allTypes: 'அனைத்து வகைகளும்',
    qualityGrade: 'தர நிலை',
    allGrades: 'அனைத்து நிலைகளும்',
    gradeAPlus: 'A+ பிரீமியம்',
    gradeA: 'A நிலை',
    gradeB: 'B நிலை',
    minPrice: 'குறைந்தபட்ச விலை',
    sortBy: 'வரிசைப்படுத்து',
    newestFirst: 'புதியது முதலில்',
    priceLowToHigh: 'விலை: குறைவானது முதல்',
    priceHighToLow: 'விலை: अधिकமானது முதல்',
    highestRated: 'அதிக மதிப்பீடு',
    availableProducts: 'கிடைக்கும் தயாரிப்புகள்',
    showing: 'காண்பிக்கப்படுகிறது',
    of: 'இல்',
    grade: 'நிலை',
    available: 'கிடைக்கிறது',
    addToCart: 'வண்டியில் சேர்',
    outOfStock: 'இருப்பு இல்லை',
    qualityDetails: 'தர விவரங்கள்',
    noProductsFound: 'தயாரிப்புகள் எதுவும் இல்லை',
    tryAdjustingFilters: 'வடிகட்டிகளை மாற்றவும்',
    clearAllFilters: 'அனைத்தையும் அழிக்கவும்',

    // Inventory
    inventoryManagement: 'சரக்கு மேலாண்மை',
    inventorySubtitle: 'கிடங்குகள் மற்றும் இருப்பு சரக்குகளை நிர்வகிக்கவும்',
    addWarehouse: 'கிடங்கைச் சேர்',
    totalWarehouses: 'மொத்த கிடங்குகள்',
    totalStock: 'மொத்த இருப்பு',
    avgUtilization: 'சராசரி பயன்பாடு',
    noWarehousesFound: 'கிடங்குகள் எதுவும் இல்லை',
    createFirstWarehouse: 'சரக்கு மேலாண்மையைத் தொடங்க உங்கள் முதல் கிடங்கை உருவாக்கவும்',
    lowStock: 'குறைந்த இருப்பு',
    capacityUtilization: 'திறன் பயன்பாடு',
    stockValue: 'இருப்பு மதிப்பு',
    totalBatches: 'மொத்த தொகுதிகள்',
    owner: 'உரிமையாளர்',
    addNewWarehouse: 'புதிய கிடங்கைச் சேர்',
    warehouseName: 'கிடங்கு பெயர்',
    location: 'இடம்',
    capacity: 'திறன்',
    description: 'விளக்கம்',
    cancel: 'ரத்துசெய்',
    createWarehouse: 'கிடங்கை உருவாக்கு',
    addBatchTo: 'தொகுதியைச் சேர்',
    batchId: 'தொகுதி ஐடி',
    weight: 'எடை',
    value: 'மதிப்பு',
    woolType: 'கம்பளி வகை',
    selectType: 'வகையைத் தேர்ந்தெடுக்கவும்',
    fineWool: 'மெல்லிய கம்பளி',
    mediumWool: 'நடுத்தர கம்பளி',
    coarseWool: 'கரடுமுரடான கம்பளி',
    qualityGrade: 'தர நிலை',
    selectGrade: 'நிலையைத் தேர்ந்தெடுக்கவும்',
    gradeAPremium: 'நிலை A (பிரீமியம்)',
    gradeBGood: 'நிலை B (நல்லது)',
    gradeCStandard: 'நிலை C (தரமானது)',
    gradeDBelowStandard: 'நிலை D (தரத்திற்குக் கீழே)',
    addBatch: 'தொகுதியைச் சேர்',
    failedToCreateWarehouse: 'கிடங்கை உருவாக்க முடியவில்லை',
    failedToAddBatch: 'கிடங்கில் தொகுதியைச் சேர்க்க முடியவில்லை',
    confirmDeleteWarehouse: 'இந்த கிடங்கை நிச்சயமாக நீக்க விரும்புகிறீர்களா?',
    failedToDeleteWarehouse: 'கிடங்கை நீக்க முடியவில்லை',
    loadingInventory: 'சரக்கு தரவு ஏற்றப்படுகிறது...',
  },

  te: { // Telugu
    loading: 'లోడ్ అవుతోంది...',
    save: 'సేవ్ చేయండి',
    cancel: 'రద్దు చేయండి',
    delete: 'తొలగించు',
    edit: 'సవరించు',
    view: 'చూడండి',
    search: 'వెతకండి',
    home: 'హోమ్',
    dashboard: 'డాష్‌బోర్డ్',
    products: 'ఉత్పత్తులు',
    marketplace: 'మార్కెట్‌ప్లేస్',
    inventory: 'జాబితా',
    processing: 'ప్రాసెసింగ్ సేవలు',
    education: 'విద్య మరియు శిక్షణ',
    profile: 'ప్రొఫైల్',
    settings: 'సెట్టింగ్‌లు',
    logout: 'లాగ్ అవుట్',
    login: 'లాగిన్',
    farmer: 'రైతు',
    buyer: 'కొనుగోలుదారుడు',
    government: 'ప్రభుత్వం',
    inspector: 'తనిఖీదారు',

    // Marketplace
    loginToPurchase: 'కొనుగోలు చేయడానికి లాగిన్ చేయండి',
    orderSuccess: 'ఆర్డర్ విజయవంతంగా ఉంచబడింది!',
    orderFailed: 'ఆర్డర్ చేయడం విఫలమైంది',
    loadingMarketplace: 'మార్కెట్‌ప్లేస్ లోడ్ అవుతోంది...',
    marketplaceTitle: 'కర్ణాటక ఉన్ని మార్కెట్',
    marketplaceSubtitle: 'కర్ణాటక అంతటా ధృవీకరించబడిన రైతుల నుండి ప్రీమియం ఉన్ని',
    availableBatches: 'అందుబాటులో ఉన్న బ్యాచ్‌లు',
    allVerified: 'అన్నీ ధృవీకరించబడ్డాయి',
    yourBatch: 'మీ బ్యాచ్',
    type: 'రకం',
    total: 'మొత్తం',
    purchaseBatch: 'బ్యాచ్ కొనండి',
    noBatchesFound: 'ఏ బ్యాచ్‌లు అందుబాటులో లేవు',
    checkBackLater: 'తర్వాత మళ్లీ తనిఖీ చేయండి',

    // Dashboard
    totalBatches: 'మొత్తం బ్యాచ్‌లు',
    totalOrders: 'మొత్తం ఆర్డర్లు',
    totalSales: 'మొత్తం అమ్మకాలు',
    rating: 'రేటింగ్',
    reviews: 'సమీక్షలు',
    approvedSales: 'ఆమోదించబడిన అమ్మకాలు',
    totalRevenue: 'మొత్తం రాబడి',
    delivered: 'డెలివరీ చేయబడింది',
    inTransit: 'రవాణాలో ఉంది',
    totalSpent: 'మొత్తం ఖర్చు',
    applications: 'అప్లికేషన్లు',
    totalValue: 'మొత్తం విలువ',
    pendingInspection: 'తనిఖీ పెండింగ్‌లో ఉంది',
    inspectedToday: 'ఈ రోజు తనిఖీ చేయబడింది',
    gradeABatches: 'గ్రేడ్ A+ బ్యాచ్‌లు',
    totalInspections: 'మొత్తం తనిఖీలు',
    quickActions: 'త్వరిత చర్యలు',
    sales: 'అమ్మకాలు',
    training: 'శిక్షణ',
    shopNow: 'ఇప్పుడే కొనండి',
    cart: 'కార్ట్',
    trackOrders: 'ఆర్డర్లను ట్రాక్ చేయండి',
    adminPanel: 'అడ్మిన్ ప్యానెల్',
    marketInfo: 'మార్కెట్ సమాచారం',
    qualityAssessment: 'నాణ్యత అంచనా',
    batchLookup: 'బ్యాచ్ శోధన',
    qualityReports: 'నాణ్యత నివేదికలు',

    // Profile
    personalInformation: 'వ్యక్తిగత సమాచారం',
    businessDetails: 'వ్యాపార వివరాలు',
    accountSettings: 'ఖాతా సెట్టింగ్‌లు',
    fullName: 'పూర్తి పేరు',
    emailAddress: 'ఇమెయిల్ చిరునామా',
    phoneNumber: 'ఫోన్ నంబర్',
    address: 'చిరునామా',
    city: 'నగరం',
    state: 'రాష్ట్రం',
    pincode: 'పిన్‌కోడ్',
    farmName: 'ఫారం పేరు',
    farmSize: 'ఫారం పరిమాణం',
    woolTypes: 'ఉన్ని రకాలు',
    businessLicense: 'వ్యాపార లైసెన్స్',
    experience: 'అనుభవం (సంవత్సరాలు)',
    specialization: 'స్పెషలైజేషన్',
    bio: 'బయో',
    profileUpdated: 'ప్రొఫైల్ విజయవంతంగా నవీకరించబడింది!',
    changePassword: 'పాస్‌వర్డ్ మార్చండి',
    exportData: 'డేటాను ఎగుమతి చేయండి',
    deactivateAccount: 'ఖాతాను నిష్క్రియం చేయండి',

    // Education
    educationTraining: 'విద్య మరియు శిక్షణ',
    courses: 'కోర్సులు',
    myCourses: 'నా కోర్సులు',
    certificates: 'సర్టిఫికేట్లు',
    progress: 'పురోగతి',
    startCourse: 'కోర్సు ప్రారంభించండి',
    completeCourse: 'కోర్సు పూర్తి చేయండి',
    loginToEnroll: 'కోర్సులలో నమోదు చేసుకోవడానికి దయచేసి లాగిన్ చేయండి',
    enrollSuccess: 'కోర్సులో విజయవంతంగా నమోదు చేయబడింది!',
    enrollFailed: 'నమోదు విఫలమైంది',
    educationTitle: 'కర్ణాటక ఉన్ని విద్య మరియు శిక్షణ కేంద్రం',
    educationSubtitle: 'నిపుణుల నుండి నేర్చుకోండి',
    backToDashboard: 'డాష్‌బోర్డ్‌కు తిరిగి వెళ్ళు',
    trainingResources: 'శిక్షణ వనరులు',
    enrollNow: 'ఇప్పుడే నమోదు చేసుకోండి',
    producerDirectory: 'ఉత్పత్తిదారుల డైరెక్టరీ',
    searchPlaceholder: 'పేరు లేదా నైపుణ్యం ద్వారా శోధించండి...',
    region: 'ప్రాంతం',
    allRegions: 'అన్ని ప్రాంతాలు',
    allStates: 'అన్ని రాష్ట్రాలు',
    contact: 'సంప్రదించండి',
    registeredProducers: 'నమోదిత ఉత్పత్తిదారులు',
    trainingCourses: 'శిక్షణ కోర్సులు',
    regionsCovered: 'కవర్ చేయబడిన ప్రాంతాలు',
    studentsEnrolled: 'నమోదైన విద్యార్థులు',

    // Product Catalog
    unknownFarmer: 'తెలియని రైతు',
    wool: 'ఉన్ని',
    highQuality: 'అధిక నాణ్యత',
    woolFrom: 'నుండి ఉన్ని',
    trustedFarmer: 'నమ్మకమైన రైతు',
    loginToAddToCart: 'కార్ట్‌కు జోడించడానికి లాగిన్ చేయండి',
    addedToCart: 'కార్ట్‌కు జోడించబడింది!',
    failedToAddToCart: 'జోడించడం విఫలమైంది',
    productCatalogTitle: 'కర్ణాటక ఉన్ని ఉత్పత్తులు',
    items: 'అంశాలు',
    viewCart: 'కార్ట్‌ను చూడండి',
    filterSearch: 'ఫిల్టర్ మరియు శోధన',
    searchProducts: 'ఉత్పత్తులను శోధించండి',
    woolType: 'ఉన్ని రకం',
    allTypes: 'అన్ని రకాలు',
    qualityGrade: 'నాణ్యత గ్రేడ్',
    allGrades: 'అన్ని గ్రేడ్‌లు',
    gradeAPlus: 'A+ ప్రీమియం',
    gradeA: 'A గ్రేడ్',
    gradeB: 'B గ్రేడ్',
    minPrice: 'కనీస ధర',
    sortBy: 'క్రమబద్ధీకరించు',
    newestFirst: 'కొత్తది మొదట',
    priceLowToHigh: 'ధర: తక్కువ నుండి ఎక్కువ',
    priceHighToLow: 'ధర: ఎక్కువ నుండి తక్కువ',
    highestRated: 'అత్యధిక రేటింగ్',
    availableProducts: 'అందుబాటులో ఉన్న ఉత్పత్తులు',
    showing: 'చూపిస్తోంది',
    of: 'లో',
    grade: 'గ్రేడ్',
    available: 'అందుబాటులో ఉంది',
    addToCart: 'కార్ట్‌కు జోడించు',
    outOfStock: 'స్టాక్ లేదు',
    qualityDetails: 'నాణ్యత వివరాలు',
    noProductsFound: 'ఉత్పత్తులు కనుగొనబడలేదు',
    tryAdjustingFilters: 'ఫిల్టర్‌లను సర్దుబాటు చేయండి',
    clearAllFilters: 'అన్నింటినీ క్లియర్ చేయండి',

    // Inventory
    inventoryManagement: 'ఇన్వెంటరీ నిర్వహణ',
    inventorySubtitle: 'గిడ్డంగులు మరియు స్టాక్ ఇన్వెంటరీని నిర్వహించండి',
    addWarehouse: 'గిడ్డంగిని జోడించు',
    totalWarehouses: 'మొత్తం గిడ్డంగులు',
    totalStock: 'మొత్తం స్టాక్',
    avgUtilization: 'సగటు వినియోగం',
    noWarehousesFound: 'గిడ్డంగులు కనుగొనబడలేదు',
    createFirstWarehouse: 'ఇన్వెంటరీ నిర్వహణను ప్రారంభించడానికి మీ మొదటి గిడ్డంగిని సృష్టించండి',
    lowStock: 'తక్కువ స్టాక్',
    capacityUtilization: 'సామర్థ్య వినియోగం',
    stockValue: 'స్టాక్ విలువ',
    totalBatches: 'మొత్తం బ్యాచ్‌లు',
    owner: 'యజమాని',
    addNewWarehouse: 'కొత్త గిడ్డంగిని జోడించు',
    warehouseName: 'గిడ్డంగి పేరు',
    location: 'స్థానం',
    capacity: 'సామర్థ్యం',
    description: 'వివరణ',
    cancel: 'రద్దు చేయి',
    createWarehouse: 'గిడ్డంగిని సృష్టించు',
    addBatchTo: 'దీనికి బ్యాచ్‌ను జోడించు',
    batchId: 'బ్యాచ్ ఐడి',
    weight: 'బరువు',
    value: 'విలువ',
    woolType: 'ఉన్ని రకం',
    selectType: 'రకాన్ని ఎంచుకోండి',
    fineWool: 'మంచి ఉన్ని',
    mediumWool: 'మధ్యస్థ ఉన్ని',
    coarseWool: 'ముతక ఉన్ని',
    qualityGrade: 'నాణ్యత గ్రేడ్',
    selectGrade: 'గ్రేడ్‌ను ఎంచుకోండి',
    gradeAPremium: 'గ్రేడ్ A (ప్రీమియం)',
    gradeBGood: 'గ్రేడ్ B (మంచిది)',
    gradeCStandard: 'గ్రేడ్ C (ప్రామాణికం)',
    gradeDBelowStandard: 'గ్రేడ్ D (ప్రమాణానికి తక్కువ)',
    addBatch: 'బ్యాచ్‌ను జోడించు',
    failedToCreateWarehouse: 'గిడ్డంగిని సృష్టించడం విఫలమైంది',
    failedToAddBatch: 'గిడ్డంగికి బ్యాచ్‌ను జోడించడం విఫలమైంది',
    confirmDeleteWarehouse: 'మీరు ఖచ్చితంగా ఈ గిడ్డంగిని తొలగించాలనుకుంటున్నారా?',
    failedToDeleteWarehouse: 'గిడ్డంగిని తొలగించడం విఫలమైంది',
    loadingInventory: 'ఇన్వెంటరీ డేటా లోడ్ అవుతోంది...',
  },

  ml: { // Malayalam
    loading: 'ലോഡുചെയ്യുന്നു...',
    save: 'സേവ് ചെയ്യുക',
    cancel: 'റദ്ദാക്കുക',
    delete: 'ഇല്ലാതാക്കുക',
    edit: 'എഡിറ്റ് ചെയ്യുക',
    view: 'കാണുക',
    search: 'തിരയുക',
    home: 'ഹോം',
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    products: 'ഉൽപ്പന്നങ്ങൾ',
    marketplace: 'മാർക്കറ്റ്പ്ലേസ്',
    inventory: 'ഇൻവെന്ററി',
    processing: 'പ്രോസസ്സിംഗ് സേവനങ്ങൾ',
    education: 'വിദ്യാഭ്യാസവും പരിശീലനവും',
    profile: 'പ്രൊഫൈൽ',
    settings: 'ക്രമീകരണങ്ങൾ',
    logout: 'ലോഗ് ഔട്ട് ചെയ്യുക',
    login: 'ലോഗിൻ',
    farmer: 'കർഷകൻ',
    buyer: 'വാങ്ങുന്നയാൾ',
    government: 'സർക്കാർ',
    inspector: 'പരിശോധകൻ',

    // Marketplace
    loginToPurchase: 'വാങ്ങാൻ ലോഗിൻ ചെയ്യുക',
    orderSuccess: 'ഓർഡർ വിജയകരമായി നൽകി!',
    orderFailed: 'ഓർഡർ നൽകുന്നതിൽ പരാജയപ്പെട്ടു',
    loadingMarketplace: 'മാർക്കറ്റ്പ്ലേസ് ലോഡുചെയ്യുന്നു...',
    marketplaceTitle: 'കർണാടക കമ്പിളി വിപണി',
    marketplaceSubtitle: 'കർണാടകയിലുടനീളമുള്ള കർഷകരിൽ നിന്നുള്ള പ്രീമിയം കമ്പിളി',
    availableBatches: 'ലഭ്യമായ ബാച്ചുകൾ',
    allVerified: 'എല്ലാം പരിശോധിച്ചു',
    yourBatch: 'നിങ്ങളുടെ ബാച്ച്',
    type: 'തരം',
    total: 'ആകെ',
    purchaseBatch: 'ബാച്ച് വാങ്ങുക',
    noBatchesFound: 'ബാച്ചുകളൊന്നും ലഭ്യമല്ല',
    checkBackLater: 'പിന്നീട് വീണ്ടും പരിശോധിക്കുക',

    // Dashboard
    totalBatches: 'ആകെ ബാച്ചുകൾ',
    totalOrders: 'ആകെ ഓർഡറുകൾ',
    totalSales: 'ആകെ വിൽപ്പന',
    rating: 'റേറ്റിംഗ്',
    reviews: 'അവലോകനങ്ങൾ',
    approvedSales: 'അംഗീകൃത വിൽപ്പന',
    totalRevenue: 'ആകെ വരുമാനം',
    delivered: 'ഡെലിവറി ചെയ്തു',
    inTransit: 'യാത്രയിലാണ്',
    totalSpent: 'ആകെ ചെലവ്',
    applications: 'അപേക്ഷകൾ',
    totalValue: 'ആകെ മൂല്യം',
    pendingInspection: 'പരിശോധന ബാക്കിയുണ്ട്',
    inspectedToday: 'ഇന്ന് പരിശോധിച്ചു',
    gradeABatches: 'ഗ്രേഡ് A+ ബാച്ചുകൾ',
    totalInspections: 'ആകെ പരിശോധനകൾ',
    quickActions: 'ദ്രുത പ്രവർത്തനങ്ങൾ',
    sales: 'വിൽപ്പന',
    training: 'പരിശീലനം',
    shopNow: 'ഇപ്പോൾ വാങ്ങുക',
    cart: 'കാർട്ട്',
    trackOrders: 'ഓർഡറുകൾ ട്രാക്കുചെയ്യുക',
    adminPanel: 'അഡ്മിൻ പാനൽ',
    marketInfo: 'വിപണി വിവരങ്ങൾ',
    qualityAssessment: 'ഗുണനിലവാര വിലയിരുത്തൽ',
    batchLookup: 'ബാച്ച് തിരയൽ',
    qualityReports: 'ഗുണനിലവാര റിപ്പോർട്ടുകൾ',

    // Profile
    personalInformation: 'വ്യക്തിഗത വിവരങ്ങൾ',
    businessDetails: 'ബിസിനസ്സ് വിശദാംശങ്ങൾ',
    accountSettings: 'അക്കൗണ്ട് ക്രമീകരണങ്ങൾ',
    fullName: 'പൂർണ്ണ നാമം',
    emailAddress: 'ഇമെയിൽ വിലാസം',
    phoneNumber: 'ഫോൺ നമ്പർ',
    address: 'വിലാസം',
    city: 'നഗരം',
    state: 'സംസ്ഥാനം',
    pincode: 'പിൻ‌കോഡ്',
    farmName: 'ഫാം പേര്',
    farmSize: 'ഫാം വലുപ്പം',
    woolTypes: 'കമ്പിളി ഇനങ്ങൾ',
    businessLicense: 'ബിസിനസ്സ് ലൈസൻസ്',
    experience: 'പ്രവൃത്തിപരിചയം',
    specialization: 'സ്പെഷ്യലൈസേഷൻ',
    bio: 'ബയോ',
    profileUpdated: 'പ്രൊഫൈൽ വിജയകരമായി അപ്‌ഡേറ്റുചെയ്‌തു!',
    changePassword: 'പാസ്‌വേഡ് മാറ്റുക',
    exportData: 'ഡാറ്റ എക്‌സ്‌പോർട്ടുചെയ്യുക',
    deactivateAccount: 'അക്കൗണ്ട് നിർജ്ജീവമാക്കുക',

    // Education
    educationTraining: 'വിദ്യാഭ്യാസവും പരിശീലനവും',
    courses: 'കോഴ്സുകൾ',
    myCourses: 'എന്റെ കോഴ്സുകൾ',
    certificates: 'സർട്ടിഫിക്കറ്റുകൾ',
    progress: 'പുരോഗതി',
    startCourse: 'കോഴ്സ് ആരംഭിക്കുക',
    completeCourse: 'കോഴ്സ് പൂർത്തിയാക്കുക',
    loginToEnroll: 'കോഴ്സുകളിൽ ചേരാൻ ലോഗിൻ ചെയ്യുക',
    enrollSuccess: 'കോഴ്സിൽ വിജയകരമായി ചേർന്നു!',
    enrollFailed: 'ചേരൽ പരാജയപ്പെട്ടു',
    educationTitle: 'കർണാടക കമ്പിളി വിദ്യാഭ്യാസ പരിശീലന കേന്ദ്രം',
    educationSubtitle: 'വിദഗ്ധരിൽ നിന്ന് പഠിക്കുക',
    backToDashboard: 'ഡാഷ്‌ബോർഡിലേക്ക് മടങ്ങുക',
    trainingResources: 'പരിശീലന വിഭവങ്ങൾ',
    enrollNow: 'ഇപ്പോൾ ചേരുക',
    producerDirectory: 'നിർമ്മാതാക്കളുടെ ഡയറക്ടറി',
    searchPlaceholder: 'പേര് അല്ലെങ്കിൽ വൈദഗ്ദ്ധ്യം ഉപയോഗിച്ച് തിരയുക...',
    region: 'പ്രദേശം',
    allRegions: 'എല്ലാ പ്രദേശങ്ങളും',
    allStates: 'എല്ലാ സംസ്ഥാനങ്ങളും',
    contact: 'ബന്ധപ്പെടുക',
    registeredProducers: 'രജിസ്റ്റർ ചെയ്ത നിർമ്മാതാക്കൾ',
    trainingCourses: 'പരിശീലന കോഴ്സുകൾ',
    regionsCovered: 'ഉൾക്കൊള്ളുന്ന പ്രദേശങ്ങൾ',
    studentsEnrolled: 'ചേർന്ന വിദ്യാർത്ഥികൾ',

    // Product Catalog
    unknownFarmer: 'അജ്ഞാത കർഷകൻ',
    wool: 'കമ്പിളി',
    highQuality: 'ഉയർന്ന നിലവാരമുള്ള',
    woolFrom: 'കമ്പിളി',
    trustedFarmer: 'വിശ്വസ്തനായ കർഷകൻ',
    loginToAddToCart: 'കാർട്ടിലേക്ക് ചേർക്കാൻ ലോഗിൻ ചെയ്യുക',
    addedToCart: 'കാർട്ടിലേക്ക് ചേർത്തു!',
    failedToAddToCart: 'ചേർക്കുന്നതിൽ പരാജയപ്പെട്ടു',
    productCatalogTitle: 'കർണാടക കമ്പിളി ഉൽപ്പന്നങ്ങൾ',
    items: 'ഇനങ്ങൾ',
    viewCart: 'കാർട്ട് കാണുക',
    filterSearch: 'ഫിൽട്ടർ & തിരയൽ',
    searchProducts: 'ഉൽപ്പന്നങ്ങൾ തിരയുക',
    woolType: 'കമ്പിളി തരം',
    allTypes: 'എല്ലാ തരങ്ങളും',
    qualityGrade: 'ഗുണനിലവാര ഗ്രേഡ്',
    allGrades: 'എല്ലാ ഗ്രേഡുകളും',
    gradeAPlus: 'A+ പ്രീമിയം',
    gradeA: 'A ഗ്രേഡ്',
    gradeB: 'B ഗ്രേഡ്',
    minPrice: 'കുറഞ്ഞ വില',
    sortBy: 'തരംതിരിക്കുക',
    newestFirst: 'പുതിയത് ആദ്യം',
    priceLowToHigh: 'വില: കുറഞ്ഞതിൽ നിന്ന്',
    priceHighToLow: 'വില: കൂടിയതിൽ നിന്ന്',
    highestRated: 'ഏറ്റവും ഉയർന്ന റേറ്റിംഗ്',
    availableProducts: 'ലഭ്യമായ ഉൽപ്പന്നങ്ങൾ',
    showing: 'കാണിക്കുന്നു',
    of: 'ന്റെ',
    grade: 'ഗ്രേഡ്',
    available: 'ലഭ്യമാണ്',
    addToCart: 'കാർട്ടിലേക്ക് ചേർക്കുക',
    outOfStock: 'സ്റ്റോക്കില്ല',
    qualityDetails: 'ഗുണനിലവാര വിശദാംശങ്ങൾ',
    noProductsFound: 'ഉൽപ്പന്നങ്ങളൊന്നും കണ്ടെത്തിയില്ല',
    tryAdjustingFilters: 'ഫിൽട്ടറുകൾ ക്രമീകരിക്കുക',
    clearAllFilters: 'എല്ലാം മായ്‌ക്കുക',

    // Inventory
    inventoryManagement: 'ഇൻവെന്ററി മാനേജ്മെന്റ്',
    inventorySubtitle: 'ഗോഡൗണുകളും സ്റ്റോക്ക് ഇൻവെന്ററിയും നിയന്ത്രിക്കുക',
    addWarehouse: 'ഗോഡൗൺ ചേർക്കുക',
    totalWarehouses: 'ആകെ ഗോഡൗണുകൾ',
    totalStock: 'ആകെ സ്റ്റോക്ക്',
    avgUtilization: 'ശരാശരി ഉപയോഗം',
    noWarehousesFound: 'ഗോഡൗണുകളൊന്നും കണ്ടെത്തിയില്ല',
    createFirstWarehouse: 'ഇൻവെന്ററി മാനേജ്മെന്റ് ആരംഭിക്കാൻ നിങ്ങളുടെ ആദ്യ ഗോഡൗൺ സൃഷ്ടിക്കുക',
    lowStock: 'കുറഞ്ഞ സ്റ്റോക്ക്',
    capacityUtilization: 'ശേഷി ഉപയോഗം',
    stockValue: 'സ്റ്റോക്ക് മൂല്യം',
    totalBatches: 'ആകെ ബാച്ചുകൾ',
    owner: 'ഉടമ',
    addNewWarehouse: 'പുതിയ ഗോഡൗൺ ചേർക്കുക',
    warehouseName: 'ഗോഡൗൺ പേര്',
    location: 'സ്ഥലം',
    capacity: 'ശേഷി',
    description: 'വിവരണം',
    cancel: 'റദ്ദാക്കുക',
    createWarehouse: 'ഗോഡൗൺ സൃഷ്ടിക്കുക',
    addBatchTo: 'ഇതിലേക്ക് ബാച്ച് ചേർക്കുക',
    batchId: 'ബാച്ച് ഐഡി',
    weight: 'ഭാരം',
    value: 'മൂല്യം',
    woolType: 'കമ്പിളി തരം',
    selectType: 'തരം തിരഞ്ഞെടുക്കുക',
    fineWool: 'നല്ല കമ്പിളി',
    mediumWool: 'ഇടത്തരം കമ്പിളി',
    coarseWool: 'പരുക്കൻ കമ്പിളി',
    qualityGrade: 'ഗുണനിലവാര ഗ്രേഡ്',
    selectGrade: 'ഗ്രേഡ് തിരഞ്ഞെടുക്കുക',
    gradeAPremium: 'ഗ്രേഡ് A (പ്രീമിയം)',
    gradeBGood: 'ഗ്രേഡ് B (നല്ലത്)',
    gradeCStandard: 'ഗ്രേഡ് C (സാധാരണം)',
    gradeDBelowStandard: 'ഗ്രേഡ് D (നിലവാരത്തിന് താഴെ)',
    addBatch: 'ബാച്ച് ചേർക്കുക',
    failedToCreateWarehouse: 'ഗോഡൗൺ സൃഷ്ടിക്കുന്നതിൽ പരാജയപ്പെട്ടു',
    failedToAddBatch: 'ഗോഡൗണിലേക്ക് ബാച്ച് ചേർക്കുന്നതിൽ പരാജയപ്പെട്ടു',
    confirmDeleteWarehouse: 'ഈ ഗോഡൗൺ നീക്കംചെയ്യണമെന്ന് നിങ്ങൾക്ക് ഉറപ്പാണോ?',
    failedToDeleteWarehouse: 'ഗോഡൗൺ നീക്കംചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു',
    loadingInventory: 'ഇൻവെന്ററി ഡാറ്റ ലോഡുചെയ്യുന്നു...',
  },

  mr: { // Marathi
    loading: 'लोड होत आहे...',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    delete: 'हटवा',
    edit: 'संपादन',
    view: 'पहा',
    search: 'शोधा',
    home: 'मुख्यपृष्ठ',
    dashboard: 'डॅशबोर्ड',
    products: 'उत्पादने',
    marketplace: 'बाजारपेठ',
    inventory: 'इन्व्हेंटरी',
    processing: 'प्रोसेसिंग सेवा',
    // Education
    educationTraining: 'शिक्षण आणि प्रशिक्षण',
    courses: 'अभ्यासक्रम',
    myCourses: 'माझे अभ्यासक्रम',
    certificates: 'प्रमाणपत्रे',
    progress: 'प्रगती',
    startCourse: 'अभ्यासक्रम सुरू करा',
    completeCourse: 'अभ्यासक्रम पूर्ण करा',
    loginToEnroll: 'अभ्यासक्रमांना नाव नोंदणी करण्यासाठी कृपया लॉगिन करा',
    enrollSuccess: 'अभ्यासक्रमात यशस्वीरित्या नाव नोंदणी केली!',
    enrollFailed: 'नाव नोंदणी अयशस्वी',
    educationTitle: 'कर्नाटक लोकर शिक्षण आणि प्रशिक्षण केंद्र',
    educationSubtitle: 'तज्ञांकडून शिका',
    backToDashboard: 'डॅशबोर्डवर परत जा',
    trainingResources: 'प्रशिक्षण संसाधने',
    enrollNow: 'आता नाव नोंदणी करा',
    producerDirectory: 'उत्पादक निर्देशिका',
    searchPlaceholder: 'नाव किंवा कौशल्य द्वारे शोधा...',
    region: 'प्रदेश',
    allRegions: 'सर्व प्रदेश',
    allStates: 'सर्व राज्ये',
    contact: 'संपर्क',
    registeredProducers: 'नोंदणीकृत उत्पादक',
    trainingCourses: 'प्रशिक्षण अभ्यासक्रम',
    regionsCovered: 'कव्हर केलेले प्रदेश',
    studentsEnrolled: 'नाव नोंदणी केलेले विद्यार्थी',

    // Product Catalog
    unknownFarmer: 'अज्ञात शेतकरी',
    wool: 'लोकर',
    highQuality: 'उच्च दर्जाचे',
    woolFrom: 'कडून लोकर',
    trustedFarmer: 'एक विश्वासार्ह शेतकरी',
    loginToAddToCart: 'कार्टमध्ये जोडण्यासाठी कृपया लॉगिन करा',
    addedToCart: 'कार्टमध्ये जोडले!',
    failedToAddToCart: 'कार्टमध्ये जोडण्यात अयशस्वी',
    productCatalogTitle: 'कर्नाटक लोकर उत्पादने',
    items: 'वस्तू',
    viewCart: 'कार्ट पहा',
    filterSearch: 'फिल्टर आणि शोधा',
    searchProducts: 'उत्पादने शोधा',
    woolType: 'लोकरीचा प्रकार',
    allTypes: 'सर्व प्रकार',
    qualityGrade: 'गुणवत्ता ग्रेड',
    allGrades: 'सर्व ग्रेड',
    gradeAPlus: 'A+ प्रीमियम',
    gradeA: 'A ग्रेड',
    gradeB: 'B ग्रेड',
    minPrice: 'किमान किंमत',
    sortBy: 'क्रमवारी लावा',
    newestFirst: 'नवीन प्रथम',
    priceLowToHigh: 'किंमत: कमी ते जास्त',
    priceHighToLow: 'किंमत: जास्त ते कमी',
    highestRated: 'सर्वाधिक रेट केलेले',
    availableProducts: 'उपलब्ध उत्पादने',
    showing: 'दाखवत आहे',
    of: 'पैकी',
    grade: 'ग्रेड',
    available: 'उपलब्ध',
    addToCart: 'कार्टमध्ये जोडा',
    outOfStock: 'स्टॉक नाही',
    qualityDetails: 'गुणवत्ता तपशील',
    noProductsFound: 'कोणतीही उत्पादने आढळली नाहीत',
    tryAdjustingFilters: 'फिल्टर समायोजित करा',
    clearAllFilters: 'सर्व साफ करा',

    // Inventory
    inventoryManagement: 'इन्व्हेंटरी व्यवस्थापन',
    inventorySubtitle: 'गोदामे आणि स्टॉक इन्व्हेंटरी व्यवस्थापित करा',
    addWarehouse: 'गोदाम जोडा',
    totalWarehouses: 'एकूण गोदामे',
    totalStock: 'एकूण स्टॉक',
    avgUtilization: 'सरासरी वापर',
    noWarehousesFound: 'कोणतीही गोदामे आढळली नाहीत',
    createFirstWarehouse: 'इन्व्हेंटरी व्यवस्थापन सुरू करण्यासाठी तुमचे पहिले गोदाम तयार करा',
    lowStock: 'कमी स्टॉक',
    capacityUtilization: 'क्षमता वापर',
    stockValue: 'स्टॉक मूल्य',
    totalBatches: 'एकूण बॅचेस',
    owner: 'मालक',
    addNewWarehouse: 'नवीन गोदाम जोडा',
    warehouseName: 'गोदामाचे नाव',
    location: 'स्थान',
    capacity: 'क्षमता',
    description: 'वर्णन',
    cancel: 'रद्द करा',
    createWarehouse: 'गोदाम तयार करा',
    addBatchTo: 'मध्ये बॅच जोडा',
    batchId: 'बॅच आयडी',
    weight: 'वजन',
    value: 'मूल्य',
    woolType: 'लोकरीचा प्रकार',
    selectType: 'प्रकार निवडा',
    fineWool: 'बारीक लोकर',
    mediumWool: 'मध्यम लोकर',
    coarseWool: 'जाड लोकर',
    qualityGrade: 'गुणवत्ता ग्रेड',
    selectGrade: 'ग्रेड निवडा',
    gradeAPremium: 'ग्रेड A (प्रीमियम)',
    gradeBGood: 'ग्रेड B (चांगले)',
    gradeCStandard: 'ग्रेड C (मानक)',
    gradeDBelowStandard: 'ग्रेड D (मानक पेक्षा कमी)',
    addBatch: 'बॅच जोडा',
    failedToCreateWarehouse: 'गोदाम तयार करण्यात अयशस्वी',
    failedToAddBatch: 'गोदामात बॅच जोडण्यात अयशस्वी',
    confirmDeleteWarehouse: 'तुम्हाला नक्की हे गोदाम हटवायचे आहे का?',
    failedToDeleteWarehouse: 'गोदाम हटवण्यात अयशस्वी',
    loadingInventory: 'इन्व्हेंटरी डेटा लोड होत आहे...',
    profile: 'प्रोफाइल',
    settings: 'सेटिंग्ज',
    logout: 'लॉग आउट',
    login: 'लॉगिन',
    farmer: 'शेतकरी',
    buyer: 'खरेदीदार',
    government: 'सरकार',
    inspector: 'निरीक्षक',

    // Marketplace
    loginToPurchase: 'खरेदी करण्यासाठी कृपया लॉगिन करा',
    orderSuccess: 'ऑर्डर यशस्वीरित्या दिली!',
    orderFailed: 'ऑर्डर देण्यात अयशस्वी',
    loadingMarketplace: 'बाजारपेठ लोड होत आहे...',
    marketplaceTitle: 'कर्नाटक लोकर बाजार',
    marketplaceSubtitle: 'कर्नाटकभरातील सत्यापित शेतकऱ्यांकडून प्रीमियम लोकर',
    availableBatches: 'उपलब्ध बॅचेस',
    allVerified: 'सर्व सत्यापित',
    yourBatch: 'तुमची बॅच',
    type: 'प्रकार',
    total: 'एकूण',
    purchaseBatch: 'बॅच खरेदी करा',
    noBatchesFound: 'कोणत्याही बॅचेस उपलब्ध नाहीत',
    checkBackLater: 'नंतर पुन्हा तपासा',

    // Dashboard
    totalBatches: 'एकूण बॅचेस',
    totalOrders: 'एकूण ऑर्डर्स',
    totalSales: 'एकूण विक्री',
    rating: 'रेटिंग',
    reviews: 'पुनरावलोकने',
    approvedSales: 'मंजूर विक्री',
    totalRevenue: 'एकूण महसूल',
    delivered: 'वितरित केले',
    inTransit: 'मार्गावर',
    totalSpent: 'एकूण खर्च',
    applications: 'अर्ज',
    totalValue: 'एकूण मूल्य',
    pendingInspection: 'तपासणी प्रलंबित',
    inspectedToday: 'आज तपासणी केली',
    gradeABatches: 'ग्रेड A+ बॅचेस',
    totalInspections: 'एकूण तपासण्या',
    quickActions: 'जलद क्रिया',
    sales: 'विक्री',
    training: 'प्रशिक्षण',
    shopNow: 'आता खरेदी करा',
    cart: 'कार्ट',
    trackOrders: 'ऑर्डर ट्रॅक करा',
    adminPanel: 'प्रशासन पॅनेल',
    marketInfo: 'बाजार माहिती',
    qualityAssessment: 'गुणवत्ता मूल्यांकन',
    batchLookup: 'बॅच शोध',
    qualityReports: 'गुणवत्ता अहवाल',

    // Profile
    personalInformation: 'वैयक्तिक माहिती',
    businessDetails: 'व्यवसाय तपशील',
    accountSettings: 'खाते सेटिंग्ज',
    fullName: 'पूर्ण नाव',
    emailAddress: 'ईमेल पत्ता',
    phoneNumber: 'फोन नंबर',
    address: 'पत्ता',
    city: 'शहर',
    state: 'राज्य',
    pincode: 'पिनकोड',
    farmName: 'फार्मचे नाव',
    farmSize: 'फार्मचा आकार',
    woolTypes: 'लोकरीचे प्रकार',
    businessLicense: 'व्यवसाय परवाना',
    experience: 'अनुभवाची वर्षे',
    specialization: 'विशेषज्ञता',
    bio: 'परिचय',
    profileUpdated: 'प्रोफाइल यशस्वीरित्या अपडेट केले!',
    changePassword: 'पासवर्ड बदला',
    exportData: 'डेटा निर्यात करा',
    deactivateAccount: 'खाते निष्क्रिय करा',
  }
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    // Load language from localStorage or default to 'en'
    return localStorage.getItem('preferredLanguage') || 'en';
  });

  useEffect(() => {
    // Save language preference to localStorage
    localStorage.setItem('preferredLanguage', currentLanguage);

    // Set document language attribute for screen readers
    document.documentElement.lang = currentLanguage;
  }, [currentLanguage]);

  const t = (key) => {
    return translations[currentLanguage]?.[key] || translations.en[key] || key;
  };

  const changeLanguage = (language) => {
    setCurrentLanguage(language);
  };

  const languages = [
    { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
    { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
    { code: 'hi', name: 'Hindi', nativeName: 'हिंदी', flag: '🇮🇳' },
    { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
    { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
    { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
    { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' }
  ];

  return (
    <LanguageContext.Provider value={{
      currentLanguage,
      changeLanguage,
      t,
      languages
    }}>
      {children}
    </LanguageContext.Provider>
  );
};